update

diff --git a/home/bin/executable_mypasswd b/home/bin/executable_mypasswd
--- a/home/bin/executable_mypasswd
+++ b/home/bin/executable_mypasswd
@@ -6,40 +6,68 @@
 
 # Configuration
 RECIPIENT="nicola.bicocchi@gmail.com"
-STORAGE_ENC="/run/user/1000/gvfs/google-drive:host=unimore.it,user=nbicocchi/0AM-alrhdq_d4Uk9PVA/0B8-alrhdq_d4MDJuVWs4NlVGMnM/1WgF9Hw3hx50XzhORJhRZmETYV1067uPB"
+STORAGE_ENC_REMOTE="/run/user/1000/gvfs/google-drive:host=unimore.it,user=nbicocchi/0AM-alrhdq_d4Uk9PVA/0B8-alrhdq_d4MDJuVWs4NlVGMnM/1WgF9Hw3hx50XzhORJhRZmETYV1067uPB"
+STORAGE_ENC_LOCAL="/tmp/mypasswd.enc"
 PASSWORD_LENGTH=8
 
 # Functions
 init() {
   case "$(uname -s)" in
     Linux*) 
-      which gpg >/dev/null 2>&1 || exit_with_msg "unable to find gpg. please install." 
-      which xclip >/dev/null 2>&1 || exit_with_msg "unable to find xclip. please install."
-      which mktemp >/dev/null 2>&1 || exit_with_msg "unable to find mktemp. please install." 
+      which gpg >/dev/null 2>&1 || error "unable to find gpg. please install." 
+      which xclip >/dev/null 2>&1 || error "unable to find xclip. please install."
+      which mktemp >/dev/null 2>&1 || error "unable to find mktemp. please install." 
       TOCLIPBOARD="xclip -selection clipboard"
       ;;
   
     Darwin*)
-      which gpg >/dev/null 2>&1 || exit_with_msg "unable to find gpg. please install." 
-      which pbcopy >/dev/null 2>&1 || exit_with_msg "unable to find pbcopy. please install." 
-      which mktemp >/dev/null 2>&1 || exit_with_msg "unable to find mktemp. please install."
+      which gpg >/dev/null 2>&1 || error "unable to find gpg. please install." 
+      which pbcopy >/dev/null 2>&1 || error "unable to find pbcopy. please install." 
+      which mktemp >/dev/null 2>&1 || error "unable to find mktemp. please install."
       TOCLIPBOARD="pbcopy"
       ;;
+
     *)  
-      exit_with_msg "Unsupported architecture"
+      error "Unsupported architecture"
     ;;
   esac
 }
 
-exit_with_msg () {
-  echo "$1" 
+error() {
+  echo "[ERROR]: $1" 
   exit 1
+}
+
+warn() {
+  echo "[WARNING]: $1" 
+}
+
+verify_keys() {
+  gpg --list-secret-keys | grep "$RECIPIENT" > /dev/null 2>&1 || error "Missing keys for "$RECIPIENT". Import with gpg --import keys"
+}
+
+verify_encoded_file() {
+  if [ -r "$STORAGE_ENC_REMOTE" ]; then
+    STORAGE_ENC="$STORAGE_ENC_REMOTE"
+    cp "$STORAGE_ENC_REMOTE" "$STORAGE_ENC_LOCAL"
+    return
+  fi
+
+  if [ -r "$STORAGE_ENC_LOCAL" ]; then
+    warn "using cached encoded file"
+    STORAGE_ENC="$STORAGE_ENC_LOCAL"
+    return
+  fi
+
+  error "encoded file unavailable"
 }
 
 # Main
 init 
-gpg --list-secret-keys | grep "$RECIPIENT" > /dev/null 2>&1 || exit_with_msg "Missing keys for "$RECIPIENT". Import with gpg --import keys"
-test $# -eq 1 || exit_with_msg "usage: $0 all|sitename|generate|edit"
+verify_encoded_file
+verify_keys
+
+test $# -eq 1 || error "usage: $0 site|all|password|edit"
 			  
 case "$1" in
   "edit")
@@ -49,7 +77,7 @@ case "$1" in
     gpg --encrypt --recipient "$RECIPIENT" --output "$STORAGE_ENC" "$STORAGE_DEC"
     rm -rfP "$STORAGE_DEC" >/dev/null 2>&1
     ;;
-  "generate") 
+  "password") 
     password=$(openssl rand -base64 "$PASSWORD_LENGTH") 
     echo "$password" 
     echo "$password" | $TOCLIPBOARD
@@ -58,7 +86,7 @@ case "$1" in
     gpg --decrypt "$STORAGE_ENC"
     ;;
   *)
-    content=$(gpg --decrypt "$STORAGE_ENC")
+    content=$(gpg --decrypt "$STORAGE_ENC" 2>/dev/null)
     echo "$content" | grep -A 2 '^#.*'$1
     echo "$content" | grep -A 2 '^#.*'$1 | tail -n 1 | $TOCLIPBOARD
     ;;
